//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}scenarioElement" minOccurs="0"/>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}table" minOccurs="0"/>
 *         &lt;element ref="{}actuator_type" minOccurs="0"/>
 *         &lt;element ref="{}queue_override" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="modStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="health_status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;minInclusive value="0.0"/>
 *             &lt;maxInclusive value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "actuator")
public class Actuator {

    protected ScenarioElement scenarioElement;
    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    protected Parameters parameters;
    protected Table table;
    @XmlElement(name = "actuator_type")
    protected ActuatorType actuatorType;
    @XmlElement(name = "queue_override")
    protected QueueOverride queueOverride;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "modStamp")
    protected String modStamp;
    @XmlAttribute(name = "health_status")
    protected Double healthStatus;

    /**
     * Gets the value of the scenarioElement property.
     * 
     * @return
     *     possible object is
     *     {@link ScenarioElement }
     *     
     */
    public ScenarioElement getScenarioElement() {
        return scenarioElement;
    }

    /**
     * Sets the value of the scenarioElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScenarioElement }
     *     
     */
    public void setScenarioElement(ScenarioElement value) {
        this.scenarioElement = value;
    }

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the actuatorType property.
     * 
     * @return
     *     possible object is
     *     {@link ActuatorType }
     *     
     */
    public ActuatorType getActuatorType() {
        return actuatorType;
    }

    /**
     * Sets the value of the actuatorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActuatorType }
     *     
     */
    public void setActuatorType(ActuatorType value) {
        this.actuatorType = value;
    }

    /**
     * Gets the value of the queueOverride property.
     * 
     * @return
     *     possible object is
     *     {@link QueueOverride }
     *     
     */
    public QueueOverride getQueueOverride() {
        return queueOverride;
    }

    /**
     * Sets the value of the queueOverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueueOverride }
     *     
     */
    public void setQueueOverride(QueueOverride value) {
        this.queueOverride = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        return modStamp;
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

    /**
     * Gets the value of the healthStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHealthStatus() {
        return healthStatus;
    }

    /**
     * Sets the value of the healthStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHealthStatus(Double value) {
        this.healthStatus = value;
    }

}
