//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}target_actuators" minOccurs="0"/>
 *         &lt;element ref="{}feedback_sensors" minOccurs="0"/>
 *         &lt;element ref="{}ActivationIntervals" minOccurs="0"/>
 *         &lt;element ref="{}table" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="IRM_ALINEA|IRM_TOD|IRM_TOS|CRM_SWARM|CRM_HERO|CRM_MPC|FRR_MPC|VSL_TOD|SIG_Pretimed|SIG_Actuated|SIG_MaxPressure|SR_Generator"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="dt" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="java_class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameters",
    "displayPosition",
    "targetActuators",
    "feedbackSensors",
    "activationIntervals",
    "table"
})
@XmlRootElement(name = "controller")
public class Controller {

    protected Parameters parameters;
    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    @XmlElement(name = "target_actuators")
    protected TargetActuators targetActuators;
    @XmlElement(name = "feedback_sensors")
    protected FeedbackSensors feedbackSensors;
    @XmlElement(name = "ActivationIntervals")
    protected ActivationIntervals activationIntervals;
    protected List<Table> table;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "dt", required = true)
    protected double dt;
    @XmlAttribute(name = "enabled", required = true)
    protected boolean enabled;
    @XmlAttribute(name = "java_class")
    protected String javaClass;

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the targetActuators property.
     * 
     * @return
     *     possible object is
     *     {@link TargetActuators }
     *     
     */
    public TargetActuators getTargetActuators() {
        return targetActuators;
    }

    /**
     * Sets the value of the targetActuators property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetActuators }
     *     
     */
    public void setTargetActuators(TargetActuators value) {
        this.targetActuators = value;
    }

    /**
     * Gets the value of the feedbackSensors property.
     * 
     * @return
     *     possible object is
     *     {@link FeedbackSensors }
     *     
     */
    public FeedbackSensors getFeedbackSensors() {
        return feedbackSensors;
    }

    /**
     * Sets the value of the feedbackSensors property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedbackSensors }
     *     
     */
    public void setFeedbackSensors(FeedbackSensors value) {
        this.feedbackSensors = value;
    }

    /**
     * Gets the value of the activationIntervals property.
     * 
     * @return
     *     possible object is
     *     {@link ActivationIntervals }
     *     
     */
    public ActivationIntervals getActivationIntervals() {
        return activationIntervals;
    }

    /**
     * Sets the value of the activationIntervals property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivationIntervals }
     *     
     */
    public void setActivationIntervals(ActivationIntervals value) {
        this.activationIntervals = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Table }
     * 
     * 
     */
    public List<Table> getTable() {
        if (table == null) {
            table = new ArrayList<Table>();
        }
        return this.table;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     */
    public double getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     */
    public void setDt(double value) {
        this.dt = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the javaClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaClass() {
        return javaClass;
    }

    /**
     * Sets the value of the javaClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaClass(String value) {
        this.javaClass = value;
    }

}
