//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="vehicle_type_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="ids" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="crudFlags" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mod_stamps" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "demand")
public class Demand {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "vehicle_type_id", required = true)
    protected long vehicleTypeId;
    @XmlAttribute(name = "ids")
    protected String ids;
    @XmlAttribute(name = "crudFlags")
    protected String crudFlags;
    @XmlAttribute(name = "mod_stamps")
    protected String modStamps;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the vehicleTypeId property.
     * 
     */
    public long getVehicleTypeId() {
        return vehicleTypeId;
    }

    /**
     * Sets the value of the vehicleTypeId property.
     * 
     */
    public void setVehicleTypeId(long value) {
        this.vehicleTypeId = value;
    }

    /**
     * Gets the value of the ids property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIds() {
        return ids;
    }

    /**
     * Sets the value of the ids property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIds(String value) {
        this.ids = value;
    }

    /**
     * Gets the value of the crudFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlags() {
        return crudFlags;
    }

    /**
     * Sets the value of the crudFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlags(String value) {
        this.crudFlags = value;
    }

    /**
     * Gets the value of the modStamps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamps() {
        return modStamps;
    }

    /**
     * Sets the value of the modStamps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamps(String value) {
        this.modStamps = value;
    }

}
