//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}demand" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="knob" type="{http://www.w3.org/2001/XMLSchema}double" default="1" />
 *       &lt;attribute name="start_time" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="dt" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="link_id_org" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="destination_network_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="std_dev_add" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="std_dev_mult" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mod_stamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "demand"
})
@XmlRootElement(name = "demandProfile")
public class DemandProfile {

    protected List<Demand> demand;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "knob")
    protected Double knob;
    @XmlAttribute(name = "start_time")
    protected Double startTime;
    @XmlAttribute(name = "dt")
    protected Double dt;
    @XmlAttribute(name = "link_id_org", required = true)
    protected long linkIdOrg;
    @XmlAttribute(name = "destination_network_id")
    protected Long destinationNetworkId;
    @XmlAttribute(name = "std_dev_add")
    protected Double stdDevAdd;
    @XmlAttribute(name = "std_dev_mult")
    protected Double stdDevMult;
    @XmlAttribute(name = "mod_stamp")
    protected String modStamp;

    /**
     * Gets the value of the demand property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the demand property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDemand().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Demand }
     * 
     * 
     */
    public List<Demand> getDemand() {
        if (demand == null) {
            demand = new ArrayList<Demand>();
        }
        return this.demand;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the knob property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getKnob() {
        if (knob == null) {
            return  1.0D;
        } else {
            return knob;
        }
    }

    /**
     * Sets the value of the knob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setKnob(Double value) {
        this.knob = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getStartTime() {
        if (startTime == null) {
            return  0.0D;
        } else {
            return startTime;
        }
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStartTime(Double value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDt(Double value) {
        this.dt = value;
    }

    /**
     * Gets the value of the linkIdOrg property.
     * 
     */
    public long getLinkIdOrg() {
        return linkIdOrg;
    }

    /**
     * Sets the value of the linkIdOrg property.
     * 
     */
    public void setLinkIdOrg(long value) {
        this.linkIdOrg = value;
    }

    /**
     * Gets the value of the destinationNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDestinationNetworkId() {
        return destinationNetworkId;
    }

    /**
     * Sets the value of the destinationNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDestinationNetworkId(Long value) {
        this.destinationNetworkId = value;
    }

    /**
     * Gets the value of the stdDevAdd property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStdDevAdd() {
        return stdDevAdd;
    }

    /**
     * Sets the value of the stdDevAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStdDevAdd(Double value) {
        this.stdDevAdd = value;
    }

    /**
     * Gets the value of the stdDevMult property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStdDevMult() {
        return stdDevMult;
    }

    /**
     * Sets the value of the stdDevMult property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStdDevMult(Double value) {
        this.stdDevMult = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        return modStamp;
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

}
