//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}link_references"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_id_destination" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "destination_network")
public class DestinationNetwork {

    @XmlElement(name = "link_references", required = true)
    protected LinkReferences linkReferences;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "link_id_destination", required = true)
    protected long linkIdDestination;

    /**
     * Gets the value of the linkReferences property.
     * 
     * @return
     *     possible object is
     *     {@link LinkReferences }
     *     
     */
    public LinkReferences getLinkReferences() {
        return linkReferences;
    }

    /**
     * Sets the value of the linkReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkReferences }
     *     
     */
    public void setLinkReferences(LinkReferences value) {
        this.linkReferences = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the linkIdDestination property.
     * 
     */
    public long getLinkIdDestination() {
        return linkIdDestination;
    }

    /**
     * Sets the value of the linkIdDestination property.
     * 
     */
    public void setLinkIdDestination(long value) {
        this.linkIdDestination = value;
    }

}
