//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="mod_stamp" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="order" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="capacity" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="capacity_drop" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="std_dev_capacity" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="free_flow_speed" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="congestion_speed" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="critical_speed" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="std_dev_free_flow_speed" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="std_dev_congestion_speed" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="jam_density" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="transition_density" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fundamentalDiagram")
public class FundamentalDiagram {

    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "mod_stamp")
    protected String modStamp;
    @XmlAttribute(name = "order")
    protected Integer order;
    @XmlAttribute(name = "capacity", required = true)
    protected double capacity;
    @XmlAttribute(name = "capacity_drop")
    protected Double capacityDrop;
    @XmlAttribute(name = "std_dev_capacity")
    protected Double stdDevCapacity;
    @XmlAttribute(name = "free_flow_speed", required = true)
    protected double freeFlowSpeed;
    @XmlAttribute(name = "congestion_speed", required = true)
    protected double congestionSpeed;
    @XmlAttribute(name = "critical_speed")
    protected Double criticalSpeed;
    @XmlAttribute(name = "std_dev_free_flow_speed")
    protected Double stdDevFreeFlowSpeed;
    @XmlAttribute(name = "std_dev_congestion_speed")
    protected Double stdDevCongestionSpeed;
    @XmlAttribute(name = "jam_density")
    protected Double jamDensity;
    @XmlAttribute(name = "transition_density")
    protected Double transitionDensity;

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        if (modStamp == null) {
            return "0";
        } else {
            return modStamp;
        }
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

    /**
     * Gets the value of the order property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOrder() {
        return order;
    }

    /**
     * Sets the value of the order property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOrder(Integer value) {
        this.order = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     */
    public double getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     */
    public void setCapacity(double value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the capacityDrop property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getCapacityDrop() {
        if (capacityDrop == null) {
            return  0.0D;
        } else {
            return capacityDrop;
        }
    }

    /**
     * Sets the value of the capacityDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCapacityDrop(Double value) {
        this.capacityDrop = value;
    }

    /**
     * Gets the value of the stdDevCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStdDevCapacity() {
        return stdDevCapacity;
    }

    /**
     * Sets the value of the stdDevCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStdDevCapacity(Double value) {
        this.stdDevCapacity = value;
    }

    /**
     * Gets the value of the freeFlowSpeed property.
     * 
     */
    public double getFreeFlowSpeed() {
        return freeFlowSpeed;
    }

    /**
     * Sets the value of the freeFlowSpeed property.
     * 
     */
    public void setFreeFlowSpeed(double value) {
        this.freeFlowSpeed = value;
    }

    /**
     * Gets the value of the congestionSpeed property.
     * 
     */
    public double getCongestionSpeed() {
        return congestionSpeed;
    }

    /**
     * Sets the value of the congestionSpeed property.
     * 
     */
    public void setCongestionSpeed(double value) {
        this.congestionSpeed = value;
    }

    /**
     * Gets the value of the criticalSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCriticalSpeed() {
        return criticalSpeed;
    }

    /**
     * Sets the value of the criticalSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCriticalSpeed(Double value) {
        this.criticalSpeed = value;
    }

    /**
     * Gets the value of the stdDevFreeFlowSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStdDevFreeFlowSpeed() {
        return stdDevFreeFlowSpeed;
    }

    /**
     * Sets the value of the stdDevFreeFlowSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStdDevFreeFlowSpeed(Double value) {
        this.stdDevFreeFlowSpeed = value;
    }

    /**
     * Gets the value of the stdDevCongestionSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getStdDevCongestionSpeed() {
        return stdDevCongestionSpeed;
    }

    /**
     * Sets the value of the stdDevCongestionSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStdDevCongestionSpeed(Double value) {
        this.stdDevCongestionSpeed = value;
    }

    /**
     * Gets the value of the jamDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJamDensity() {
        return jamDensity;
    }

    /**
     * Sets the value of the jamDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJamDensity(Double value) {
        this.jamDensity = value;
    }

    /**
     * Gets the value of the transitionDensity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransitionDensity() {
        return transitionDensity;
    }

    /**
     * Sets the value of the transitionDensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransitionDensity(Double value) {
        this.transitionDensity = value;
    }

}
