//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}fundamentalDiagram" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}fundamentalDiagramType" minOccurs="0"/>
 *         &lt;element ref="{}calibrationAlgorithmType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="sensor_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="start_time" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="dt" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mod_stamp" type="{http://www.w3.org/2001/XMLSchema}string" default="0" />
 *       &lt;attribute name="agg_run_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundamentalDiagram",
    "fundamentalDiagramType",
    "calibrationAlgorithmType"
})
@XmlRootElement(name = "fundamentalDiagramProfile")
public class FundamentalDiagramProfile {

    protected List<FundamentalDiagram> fundamentalDiagram;
    protected FundamentalDiagramType fundamentalDiagramType;
    protected CalibrationAlgorithmType calibrationAlgorithmType;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "link_id", required = true)
    protected long linkId;
    @XmlAttribute(name = "sensor_id")
    protected Long sensorId;
    @XmlAttribute(name = "start_time")
    protected Double startTime;
    @XmlAttribute(name = "dt")
    protected Double dt;
    @XmlAttribute(name = "mod_stamp")
    protected String modStamp;
    @XmlAttribute(name = "agg_run_id")
    protected Long aggRunId;

    /**
     * Gets the value of the fundamentalDiagram property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundamentalDiagram property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundamentalDiagram().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FundamentalDiagram }
     * 
     * 
     */
    public List<FundamentalDiagram> getFundamentalDiagram() {
        if (fundamentalDiagram == null) {
            fundamentalDiagram = new ArrayList<FundamentalDiagram>();
        }
        return this.fundamentalDiagram;
    }

    /**
     * Gets the value of the fundamentalDiagramType property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalDiagramType }
     *     
     */
    public FundamentalDiagramType getFundamentalDiagramType() {
        return fundamentalDiagramType;
    }

    /**
     * Sets the value of the fundamentalDiagramType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalDiagramType }
     *     
     */
    public void setFundamentalDiagramType(FundamentalDiagramType value) {
        this.fundamentalDiagramType = value;
    }

    /**
     * Gets the value of the calibrationAlgorithmType property.
     * 
     * @return
     *     possible object is
     *     {@link CalibrationAlgorithmType }
     *     
     */
    public CalibrationAlgorithmType getCalibrationAlgorithmType() {
        return calibrationAlgorithmType;
    }

    /**
     * Sets the value of the calibrationAlgorithmType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalibrationAlgorithmType }
     *     
     */
    public void setCalibrationAlgorithmType(CalibrationAlgorithmType value) {
        this.calibrationAlgorithmType = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the linkId property.
     * 
     */
    public long getLinkId() {
        return linkId;
    }

    /**
     * Sets the value of the linkId property.
     * 
     */
    public void setLinkId(long value) {
        this.linkId = value;
    }

    /**
     * Gets the value of the sensorId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSensorId() {
        return sensorId;
    }

    /**
     * Sets the value of the sensorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSensorId(Long value) {
        this.sensorId = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getStartTime() {
        if (startTime == null) {
            return  0.0D;
        } else {
            return startTime;
        }
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setStartTime(Double value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDt(Double value) {
        this.dt = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        if (modStamp == null) {
            return "0";
        } else {
            return modStamp;
        }
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

    /**
     * Gets the value of the aggRunId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAggRunId() {
        return aggRunId;
    }

    /**
     * Sets the value of the aggRunId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAggRunId(Long value) {
        this.aggRunId = value;
    }

}
