//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="link_a" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_b" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "linkpair")
public class Linkpair {

    @XmlAttribute(name = "link_a", required = true)
    protected long linkA;
    @XmlAttribute(name = "link_b", required = true)
    protected long linkB;

    /**
     * Gets the value of the linkA property.
     * 
     */
    public long getLinkA() {
        return linkA;
    }

    /**
     * Sets the value of the linkA property.
     * 
     */
    public void setLinkA(long value) {
        this.linkA = value;
    }

    /**
     * Gets the value of the linkB property.
     * 
     */
    public long getLinkB() {
        return linkB;
    }

    /**
     * Sets the value of the linkB property.
     * 
     */
    public void setLinkB(long value) {
        this.linkB = value;
    }

}
