//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}begin" minOccurs="0"/>
 *         &lt;element ref="{}end" minOccurs="0"/>
 *         &lt;element ref="{}roads" minOccurs="0"/>
 *         &lt;element ref="{}dynamics" minOccurs="0"/>
 *         &lt;element ref="{}position" minOccurs="0"/>
 *         &lt;element ref="{}shape" minOccurs="0"/>
 *         &lt;element ref="{}link_type" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lanes" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="lane_offset" type="{http://www.w3.org/2001/XMLSchema}double" default="0" />
 *       &lt;attribute name="length" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="speed_limit" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="link_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mod_stamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="in_sync" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="priority">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "link")
public class Link {

    protected Begin begin;
    protected End end;
    protected Roads roads;
    protected Dynamics dynamics;
    protected Position position;
    protected String shape;
    @XmlElement(name = "link_type")
    protected LinkType linkType;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "lanes", required = true)
    protected double lanes;
    @XmlAttribute(name = "lane_offset")
    protected Double laneOffset;
    @XmlAttribute(name = "length", required = true)
    protected double length;
    @XmlAttribute(name = "speed_limit")
    protected Double speedLimit;
    @XmlAttribute(name = "link_name")
    protected String linkName;
    @XmlAttribute(name = "mod_stamp")
    protected String modStamp;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "in_sync")
    protected Boolean inSync;
    @XmlAttribute(name = "priority")
    protected BigDecimal priority;

    /**
     * Gets the value of the begin property.
     * 
     * @return
     *     possible object is
     *     {@link Begin }
     *     
     */
    public Begin getBegin() {
        return begin;
    }

    /**
     * Sets the value of the begin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Begin }
     *     
     */
    public void setBegin(Begin value) {
        this.begin = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link End }
     *     
     */
    public End getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link End }
     *     
     */
    public void setEnd(End value) {
        this.end = value;
    }

    /**
     * Gets the value of the roads property.
     * 
     * @return
     *     possible object is
     *     {@link Roads }
     *     
     */
    public Roads getRoads() {
        return roads;
    }

    /**
     * Sets the value of the roads property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roads }
     *     
     */
    public void setRoads(Roads value) {
        this.roads = value;
    }

    /**
     * Gets the value of the dynamics property.
     * 
     * @return
     *     possible object is
     *     {@link Dynamics }
     *     
     */
    public Dynamics getDynamics() {
        return dynamics;
    }

    /**
     * Sets the value of the dynamics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dynamics }
     *     
     */
    public void setDynamics(Dynamics value) {
        this.dynamics = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the shape property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShape() {
        return shape;
    }

    /**
     * Sets the value of the shape property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShape(String value) {
        this.shape = value;
    }

    /**
     * Gets the value of the linkType property.
     * 
     * @return
     *     possible object is
     *     {@link LinkType }
     *     
     */
    public LinkType getLinkType() {
        return linkType;
    }

    /**
     * Sets the value of the linkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkType }
     *     
     */
    public void setLinkType(LinkType value) {
        this.linkType = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the lanes property.
     * 
     */
    public double getLanes() {
        return lanes;
    }

    /**
     * Sets the value of the lanes property.
     * 
     */
    public void setLanes(double value) {
        this.lanes = value;
    }

    /**
     * Gets the value of the laneOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getLaneOffset() {
        if (laneOffset == null) {
            return  0.0D;
        } else {
            return laneOffset;
        }
    }

    /**
     * Sets the value of the laneOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLaneOffset(Double value) {
        this.laneOffset = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public double getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(double value) {
        this.length = value;
    }

    /**
     * Gets the value of the speedLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpeedLimit() {
        return speedLimit;
    }

    /**
     * Sets the value of the speedLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpeedLimit(Double value) {
        this.speedLimit = value;
    }

    /**
     * Gets the value of the linkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkName() {
        return linkName;
    }

    /**
     * Sets the value of the linkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkName(String value) {
        this.linkName = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        return modStamp;
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the inSync property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInSync() {
        if (inSync == null) {
            return true;
        } else {
            return inSync;
        }
    }

    /**
     * Sets the value of the inSync property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInSync(Boolean value) {
        this.inSync = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPriority(BigDecimal value) {
        this.priority = value;
    }

}
