//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}roadway_markers" minOccurs="0"/>
 *         &lt;element ref="{}outputs"/>
 *         &lt;element ref="{}inputs"/>
 *         &lt;element ref="{}position" minOccurs="0"/>
 *         &lt;element ref="{}node_type" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="node_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="in_sync" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="mod_stamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "node")
public class Node {

    @XmlElement(name = "roadway_markers")
    protected RoadwayMarkers roadwayMarkers;
    @XmlElement(required = true)
    protected Outputs outputs;
    @XmlElement(required = true)
    protected Inputs inputs;
    protected Position position;
    @XmlElement(name = "node_type")
    protected NodeType nodeType;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "node_name")
    protected String nodeName;
    @XmlAttribute(name = "in_sync")
    protected Boolean inSync;
    @XmlAttribute(name = "mod_stamp")
    protected String modStamp;

    /**
     * Gets the value of the roadwayMarkers property.
     * 
     * @return
     *     possible object is
     *     {@link RoadwayMarkers }
     *     
     */
    public RoadwayMarkers getRoadwayMarkers() {
        return roadwayMarkers;
    }

    /**
     * Sets the value of the roadwayMarkers property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadwayMarkers }
     *     
     */
    public void setRoadwayMarkers(RoadwayMarkers value) {
        this.roadwayMarkers = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Inputs }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inputs }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Position }
     *     
     */
    public Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Position }
     *     
     */
    public void setPosition(Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the nodeType property.
     * 
     * @return
     *     possible object is
     *     {@link NodeType }
     *     
     */
    public NodeType getNodeType() {
        return nodeType;
    }

    /**
     * Sets the value of the nodeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeType }
     *     
     */
    public void setNodeType(NodeType value) {
        this.nodeType = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the nodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * Sets the value of the nodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeName(String value) {
        this.nodeName = value;
    }

    /**
     * Gets the value of the inSync property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInSync() {
        if (inSync == null) {
            return true;
        } else {
            return inSync;
        }
    }

    /**
     * Sets the value of the inSync property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInSync(Boolean value) {
        this.inSync = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        return modStamp;
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

}
