//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Shape_QNAME = new QName("", "shape");
    private final static QName _Units_QNAME = new QName("", "units");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FundamentalDiagram }
     * 
     */
    public FundamentalDiagram createFundamentalDiagram() {
        return new FundamentalDiagram();
    }

    /**
     * Create an instance of {@link DisplayPosition }
     * 
     */
    public DisplayPosition createDisplayPosition() {
        return new DisplayPosition();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link DestinationNetwork }
     * 
     */
    public DestinationNetwork createDestinationNetwork() {
        return new DestinationNetwork();
    }

    /**
     * Create an instance of {@link LinkReferences }
     * 
     */
    public LinkReferences createLinkReferences() {
        return new LinkReferences();
    }

    /**
     * Create an instance of {@link LinkReference }
     * 
     */
    public LinkReference createLinkReference() {
        return new LinkReference();
    }

    /**
     * Create an instance of {@link DownstreamBoundaryCapacityProfile }
     * 
     */
    public DownstreamBoundaryCapacityProfile createDownstreamBoundaryCapacityProfile() {
        return new DownstreamBoundaryCapacityProfile();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Actuator }
     * 
     */
    public Actuator createActuator() {
        return new Actuator();
    }

    /**
     * Create an instance of {@link ScenarioElement }
     * 
     */
    public ScenarioElement createScenarioElement() {
        return new ScenarioElement();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link ColumnNames }
     * 
     */
    public ColumnNames createColumnNames() {
        return new ColumnNames();
    }

    /**
     * Create an instance of {@link ColumnName }
     * 
     */
    public ColumnName createColumnName() {
        return new ColumnName();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ActuatorType }
     * 
     */
    public ActuatorType createActuatorType() {
        return new ActuatorType();
    }

    /**
     * Create an instance of {@link QueueOverride }
     * 
     */
    public QueueOverride createQueueOverride() {
        return new QueueOverride();
    }

    /**
     * Create an instance of {@link Splitratio }
     * 
     */
    public Splitratio createSplitratio() {
        return new Splitratio();
    }

    /**
     * Create an instance of {@link Sensor }
     * 
     */
    public Sensor createSensor() {
        return new Sensor();
    }

    /**
     * Create an instance of {@link SensorType }
     * 
     */
    public SensorType createSensorType() {
        return new SensorType();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link TargetElements }
     * 
     */
    public TargetElements createTargetElements() {
        return new TargetElements();
    }

    /**
     * Create an instance of {@link SplitratioEvent }
     * 
     */
    public SplitratioEvent createSplitratioEvent() {
        return new SplitratioEvent();
    }

    /**
     * Create an instance of {@link Weavingfactors }
     * 
     */
    public Weavingfactors createWeavingfactors() {
        return new Weavingfactors();
    }

    /**
     * Create an instance of {@link Demand }
     * 
     */
    public Demand createDemand() {
        return new Demand();
    }

    /**
     * Create an instance of {@link TargetActuators }
     * 
     */
    public TargetActuators createTargetActuators() {
        return new TargetActuators();
    }

    /**
     * Create an instance of {@link TargetActuator }
     * 
     */
    public TargetActuator createTargetActuator() {
        return new TargetActuator();
    }

    /**
     * Create an instance of {@link ActuatorSet }
     * 
     */
    public ActuatorSet createActuatorSet() {
        return new ActuatorSet();
    }

    /**
     * Create an instance of {@link FundamentalDiagramProfile }
     * 
     */
    public FundamentalDiagramProfile createFundamentalDiagramProfile() {
        return new FundamentalDiagramProfile();
    }

    /**
     * Create an instance of {@link FundamentalDiagramType }
     * 
     */
    public FundamentalDiagramType createFundamentalDiagramType() {
        return new FundamentalDiagramType();
    }

    /**
     * Create an instance of {@link CalibrationAlgorithmType }
     * 
     */
    public CalibrationAlgorithmType createCalibrationAlgorithmType() {
        return new CalibrationAlgorithmType();
    }

    /**
     * Create an instance of {@link VehicleTypeSet }
     * 
     */
    public VehicleTypeSet createVehicleTypeSet() {
        return new VehicleTypeSet();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link RoadwayMarkers }
     * 
     */
    public RoadwayMarkers createRoadwayMarkers() {
        return new RoadwayMarkers();
    }

    /**
     * Create an instance of {@link Marker }
     * 
     */
    public Marker createMarker() {
        return new Marker();
    }

    /**
     * Create an instance of {@link Outputs }
     * 
     */
    public Outputs createOutputs() {
        return new Outputs();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Inputs }
     * 
     */
    public Inputs createInputs() {
        return new Inputs();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link ControllerSet }
     * 
     */
    public ControllerSet createControllerSet() {
        return new ControllerSet();
    }

    /**
     * Create an instance of {@link Controller }
     * 
     */
    public Controller createController() {
        return new Controller();
    }

    /**
     * Create an instance of {@link FeedbackSensors }
     * 
     */
    public FeedbackSensors createFeedbackSensors() {
        return new FeedbackSensors();
    }

    /**
     * Create an instance of {@link FeedbackSensor }
     * 
     */
    public FeedbackSensor createFeedbackSensor() {
        return new FeedbackSensor();
    }

    /**
     * Create an instance of {@link ActivationIntervals }
     * 
     */
    public ActivationIntervals createActivationIntervals() {
        return new ActivationIntervals();
    }

    /**
     * Create an instance of {@link Interval }
     * 
     */
    public Interval createInterval() {
        return new Interval();
    }

    /**
     * Create an instance of {@link SplitRatioSet }
     * 
     */
    public SplitRatioSet createSplitRatioSet() {
        return new SplitRatioSet();
    }

    /**
     * Create an instance of {@link SplitRatioProfile }
     * 
     */
    public SplitRatioProfile createSplitRatioProfile() {
        return new SplitRatioProfile();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link NetworkSet }
     * 
     */
    public NetworkSet createNetworkSet() {
        return new NetworkSet();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link LinkList }
     * 
     */
    public LinkList createLinkList() {
        return new LinkList();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Begin }
     * 
     */
    public Begin createBegin() {
        return new Begin();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link Roads }
     * 
     */
    public Roads createRoads() {
        return new Roads();
    }

    /**
     * Create an instance of {@link Road }
     * 
     */
    public Road createRoad() {
        return new Road();
    }

    /**
     * Create an instance of {@link Dynamics }
     * 
     */
    public Dynamics createDynamics() {
        return new Dynamics();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link SignalSet }
     * 
     */
    public SignalSet createSignalSet() {
        return new SignalSet();
    }

    /**
     * Create an instance of {@link Signal }
     * 
     */
    public Signal createSignal() {
        return new Signal();
    }

    /**
     * Create an instance of {@link Phase }
     * 
     */
    public Phase createPhase() {
        return new Phase();
    }

    /**
     * Create an instance of {@link SensorSet }
     * 
     */
    public SensorSet createSensorSet() {
        return new SensorSet();
    }

    /**
     * Create an instance of {@link InitialDensitySet }
     * 
     */
    public InitialDensitySet createInitialDensitySet() {
        return new InitialDensitySet();
    }

    /**
     * Create an instance of {@link Density }
     * 
     */
    public Density createDensity() {
        return new Density();
    }

    /**
     * Create an instance of {@link WeavingFactorSet }
     * 
     */
    public WeavingFactorSet createWeavingFactorSet() {
        return new WeavingFactorSet();
    }

    /**
     * Create an instance of {@link DownstreamBoundaryCapacitySet }
     * 
     */
    public DownstreamBoundaryCapacitySet createDownstreamBoundaryCapacitySet() {
        return new DownstreamBoundaryCapacitySet();
    }

    /**
     * Create an instance of {@link EventSet }
     * 
     */
    public EventSet createEventSet() {
        return new EventSet();
    }

    /**
     * Create an instance of {@link DemandSet }
     * 
     */
    public DemandSet createDemandSet() {
        return new DemandSet();
    }

    /**
     * Create an instance of {@link DemandProfile }
     * 
     */
    public DemandProfile createDemandProfile() {
        return new DemandProfile();
    }

    /**
     * Create an instance of {@link FundamentalDiagramSet }
     * 
     */
    public FundamentalDiagramSet createFundamentalDiagramSet() {
        return new FundamentalDiagramSet();
    }

    /**
     * Create an instance of {@link NetworkConnections }
     * 
     */
    public NetworkConnections createNetworkConnections() {
        return new NetworkConnections();
    }

    /**
     * Create an instance of {@link Networkpair }
     * 
     */
    public Networkpair createNetworkpair() {
        return new Networkpair();
    }

    /**
     * Create an instance of {@link Linkpair }
     * 
     */
    public Linkpair createLinkpair() {
        return new Linkpair();
    }

    /**
     * Create an instance of {@link DestinationNetworks }
     * 
     */
    public DestinationNetworks createDestinationNetworks() {
        return new DestinationNetworks();
    }

    /**
     * Create an instance of {@link RouteSet }
     * 
     */
    public RouteSet createRouteSet() {
        return new RouteSet();
    }

    /**
     * Create an instance of {@link Route }
     * 
     */
    public Route createRoute() {
        return new Route();
    }

    /**
     * Create an instance of {@link RouteLink }
     * 
     */
    public RouteLink createRouteLink() {
        return new RouteLink();
    }

    /**
     * Create an instance of {@link Duration }
     * 
     */
    public Duration createDuration() {
        return new Duration();
    }

    /**
     * Create an instance of {@link DateTime }
     * 
     */
    public DateTime createDateTime() {
        return new DateTime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "shape")
    public JAXBElement<String> createShape(String value) {
        return new JAXBElement<String>(_Shape_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units")
    public JAXBElement<String> createUnits(String value) {
        return new JAXBElement<String>(_Units_QNAME, String.class, null, value);
    }

}
