//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}link_references" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="nema" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="protected" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="permissive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="lag" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="recall" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="yellow_time" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="red_clear_time" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="min_green_time" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "phase")
public class Phase {

    @XmlElement(name = "link_references")
    protected LinkReferences linkReferences;
    @XmlAttribute(name = "nema", required = true)
    protected BigInteger nema;
    @XmlAttribute(name = "protected")
    protected Boolean _protected;
    @XmlAttribute(name = "permissive")
    protected Boolean permissive;
    @XmlAttribute(name = "lag")
    protected Boolean lag;
    @XmlAttribute(name = "recall")
    protected Boolean recall;
    @XmlAttribute(name = "yellow_time", required = true)
    protected double yellowTime;
    @XmlAttribute(name = "red_clear_time", required = true)
    protected double redClearTime;
    @XmlAttribute(name = "min_green_time", required = true)
    protected double minGreenTime;

    /**
     * Gets the value of the linkReferences property.
     * 
     * @return
     *     possible object is
     *     {@link LinkReferences }
     *     
     */
    public LinkReferences getLinkReferences() {
        return linkReferences;
    }

    /**
     * Sets the value of the linkReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinkReferences }
     *     
     */
    public void setLinkReferences(LinkReferences value) {
        this.linkReferences = value;
    }

    /**
     * Gets the value of the nema property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNema() {
        return nema;
    }

    /**
     * Sets the value of the nema property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNema(BigInteger value) {
        this.nema = value;
    }

    /**
     * Gets the value of the protected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isProtected() {
        if (_protected == null) {
            return false;
        } else {
            return _protected;
        }
    }

    /**
     * Sets the value of the protected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProtected(Boolean value) {
        this._protected = value;
    }

    /**
     * Gets the value of the permissive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPermissive() {
        if (permissive == null) {
            return false;
        } else {
            return permissive;
        }
    }

    /**
     * Sets the value of the permissive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPermissive(Boolean value) {
        this.permissive = value;
    }

    /**
     * Gets the value of the lag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLag() {
        if (lag == null) {
            return false;
        } else {
            return lag;
        }
    }

    /**
     * Sets the value of the lag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLag(Boolean value) {
        this.lag = value;
    }

    /**
     * Gets the value of the recall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRecall() {
        if (recall == null) {
            return false;
        } else {
            return recall;
        }
    }

    /**
     * Sets the value of the recall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecall(Boolean value) {
        this.recall = value;
    }

    /**
     * Gets the value of the yellowTime property.
     * 
     */
    public double getYellowTime() {
        return yellowTime;
    }

    /**
     * Sets the value of the yellowTime property.
     * 
     */
    public void setYellowTime(double value) {
        this.yellowTime = value;
    }

    /**
     * Gets the value of the redClearTime property.
     * 
     */
    public double getRedClearTime() {
        return redClearTime;
    }

    /**
     * Sets the value of the redClearTime property.
     * 
     */
    public void setRedClearTime(double value) {
        this.redClearTime = value;
    }

    /**
     * Gets the value of the minGreenTime property.
     * 
     */
    public double getMinGreenTime() {
        return minGreenTime;
    }

    /**
     * Sets the value of the minGreenTime property.
     * 
     */
    public void setMinGreenTime(double value) {
        this.minGreenTime = value;
    }

}
