//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}settings" minOccurs="0"/>
 *         &lt;element ref="{}NetworkSet" minOccurs="0"/>
 *         &lt;element ref="{}VehicleTypeSet"/>
 *         &lt;element ref="{}SignalSet" minOccurs="0"/>
 *         &lt;element ref="{}ActuatorSet" minOccurs="0"/>
 *         &lt;element ref="{}SensorSet" minOccurs="0"/>
 *         &lt;element ref="{}InitialDensitySet" minOccurs="0"/>
 *         &lt;element ref="{}WeavingFactorSet" minOccurs="0"/>
 *         &lt;element ref="{}SplitRatioSet" minOccurs="0"/>
 *         &lt;element ref="{}DownstreamBoundaryCapacitySet" minOccurs="0"/>
 *         &lt;element ref="{}EventSet" minOccurs="0"/>
 *         &lt;element ref="{}DemandSet" minOccurs="0"/>
 *         &lt;element ref="{}ControllerSet" minOccurs="0"/>
 *         &lt;element ref="{}FundamentalDiagramSet" minOccurs="0"/>
 *         &lt;element ref="{}NetworkConnections" minOccurs="0"/>
 *         &lt;element ref="{}DestinationNetworks" minOccurs="0"/>
 *         &lt;element ref="{}RouteSet" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="project_id" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lockedForEdit" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="lockedForHistory" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "scenario")
public class Scenario {

    protected String description;
    protected Settings settings;
    @XmlElement(name = "NetworkSet")
    protected NetworkSet networkSet;
    @XmlElement(name = "VehicleTypeSet", required = true)
    protected VehicleTypeSet vehicleTypeSet;
    @XmlElement(name = "SignalSet")
    protected SignalSet signalSet;
    @XmlElement(name = "ActuatorSet")
    protected ActuatorSet actuatorSet;
    @XmlElement(name = "SensorSet")
    protected SensorSet sensorSet;
    @XmlElement(name = "InitialDensitySet")
    protected InitialDensitySet initialDensitySet;
    @XmlElement(name = "WeavingFactorSet")
    protected WeavingFactorSet weavingFactorSet;
    @XmlElement(name = "SplitRatioSet")
    protected SplitRatioSet splitRatioSet;
    @XmlElement(name = "DownstreamBoundaryCapacitySet")
    protected DownstreamBoundaryCapacitySet downstreamBoundaryCapacitySet;
    @XmlElement(name = "EventSet")
    protected EventSet eventSet;
    @XmlElement(name = "DemandSet")
    protected DemandSet demandSet;
    @XmlElement(name = "ControllerSet")
    protected ControllerSet controllerSet;
    @XmlElement(name = "FundamentalDiagramSet")
    protected FundamentalDiagramSet fundamentalDiagramSet;
    @XmlElement(name = "NetworkConnections")
    protected NetworkConnections networkConnections;
    @XmlElement(name = "DestinationNetworks")
    protected DestinationNetworks destinationNetworks;
    @XmlElement(name = "RouteSet")
    protected RouteSet routeSet;
    @XmlAttribute(name = "project_id")
    protected Long projectId;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;
    @XmlAttribute(name = "lockedForEdit")
    protected Boolean lockedForEdit;
    @XmlAttribute(name = "lockedForHistory")
    protected Boolean lockedForHistory;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the networkSet property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkSet }
     *     
     */
    public NetworkSet getNetworkSet() {
        return networkSet;
    }

    /**
     * Sets the value of the networkSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkSet }
     *     
     */
    public void setNetworkSet(NetworkSet value) {
        this.networkSet = value;
    }

    /**
     * Gets the value of the vehicleTypeSet property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleTypeSet }
     *     
     */
    public VehicleTypeSet getVehicleTypeSet() {
        return vehicleTypeSet;
    }

    /**
     * Sets the value of the vehicleTypeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleTypeSet }
     *     
     */
    public void setVehicleTypeSet(VehicleTypeSet value) {
        this.vehicleTypeSet = value;
    }

    /**
     * Gets the value of the signalSet property.
     * 
     * @return
     *     possible object is
     *     {@link SignalSet }
     *     
     */
    public SignalSet getSignalSet() {
        return signalSet;
    }

    /**
     * Sets the value of the signalSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalSet }
     *     
     */
    public void setSignalSet(SignalSet value) {
        this.signalSet = value;
    }

    /**
     * Gets the value of the actuatorSet property.
     * 
     * @return
     *     possible object is
     *     {@link ActuatorSet }
     *     
     */
    public ActuatorSet getActuatorSet() {
        return actuatorSet;
    }

    /**
     * Sets the value of the actuatorSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActuatorSet }
     *     
     */
    public void setActuatorSet(ActuatorSet value) {
        this.actuatorSet = value;
    }

    /**
     * Gets the value of the sensorSet property.
     * 
     * @return
     *     possible object is
     *     {@link SensorSet }
     *     
     */
    public SensorSet getSensorSet() {
        return sensorSet;
    }

    /**
     * Sets the value of the sensorSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorSet }
     *     
     */
    public void setSensorSet(SensorSet value) {
        this.sensorSet = value;
    }

    /**
     * Gets the value of the initialDensitySet property.
     * 
     * @return
     *     possible object is
     *     {@link InitialDensitySet }
     *     
     */
    public InitialDensitySet getInitialDensitySet() {
        return initialDensitySet;
    }

    /**
     * Sets the value of the initialDensitySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialDensitySet }
     *     
     */
    public void setInitialDensitySet(InitialDensitySet value) {
        this.initialDensitySet = value;
    }

    /**
     * Gets the value of the weavingFactorSet property.
     * 
     * @return
     *     possible object is
     *     {@link WeavingFactorSet }
     *     
     */
    public WeavingFactorSet getWeavingFactorSet() {
        return weavingFactorSet;
    }

    /**
     * Sets the value of the weavingFactorSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeavingFactorSet }
     *     
     */
    public void setWeavingFactorSet(WeavingFactorSet value) {
        this.weavingFactorSet = value;
    }

    /**
     * Gets the value of the splitRatioSet property.
     * 
     * @return
     *     possible object is
     *     {@link SplitRatioSet }
     *     
     */
    public SplitRatioSet getSplitRatioSet() {
        return splitRatioSet;
    }

    /**
     * Sets the value of the splitRatioSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitRatioSet }
     *     
     */
    public void setSplitRatioSet(SplitRatioSet value) {
        this.splitRatioSet = value;
    }

    /**
     * Gets the value of the downstreamBoundaryCapacitySet property.
     * 
     * @return
     *     possible object is
     *     {@link DownstreamBoundaryCapacitySet }
     *     
     */
    public DownstreamBoundaryCapacitySet getDownstreamBoundaryCapacitySet() {
        return downstreamBoundaryCapacitySet;
    }

    /**
     * Sets the value of the downstreamBoundaryCapacitySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownstreamBoundaryCapacitySet }
     *     
     */
    public void setDownstreamBoundaryCapacitySet(DownstreamBoundaryCapacitySet value) {
        this.downstreamBoundaryCapacitySet = value;
    }

    /**
     * Gets the value of the eventSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventSet }
     *     
     */
    public EventSet getEventSet() {
        return eventSet;
    }

    /**
     * Sets the value of the eventSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSet }
     *     
     */
    public void setEventSet(EventSet value) {
        this.eventSet = value;
    }

    /**
     * Gets the value of the demandSet property.
     * 
     * @return
     *     possible object is
     *     {@link DemandSet }
     *     
     */
    public DemandSet getDemandSet() {
        return demandSet;
    }

    /**
     * Sets the value of the demandSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandSet }
     *     
     */
    public void setDemandSet(DemandSet value) {
        this.demandSet = value;
    }

    /**
     * Gets the value of the controllerSet property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerSet }
     *     
     */
    public ControllerSet getControllerSet() {
        return controllerSet;
    }

    /**
     * Sets the value of the controllerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerSet }
     *     
     */
    public void setControllerSet(ControllerSet value) {
        this.controllerSet = value;
    }

    /**
     * Gets the value of the fundamentalDiagramSet property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalDiagramSet }
     *     
     */
    public FundamentalDiagramSet getFundamentalDiagramSet() {
        return fundamentalDiagramSet;
    }

    /**
     * Sets the value of the fundamentalDiagramSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalDiagramSet }
     *     
     */
    public void setFundamentalDiagramSet(FundamentalDiagramSet value) {
        this.fundamentalDiagramSet = value;
    }

    /**
     * Gets the value of the networkConnections property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkConnections }
     *     
     */
    public NetworkConnections getNetworkConnections() {
        return networkConnections;
    }

    /**
     * Sets the value of the networkConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkConnections }
     *     
     */
    public void setNetworkConnections(NetworkConnections value) {
        this.networkConnections = value;
    }

    /**
     * Gets the value of the destinationNetworks property.
     * 
     * @return
     *     possible object is
     *     {@link DestinationNetworks }
     *     
     */
    public DestinationNetworks getDestinationNetworks() {
        return destinationNetworks;
    }

    /**
     * Sets the value of the destinationNetworks property.
     * 
     * @param value
     *     allowed object is
     *     {@link DestinationNetworks }
     *     
     */
    public void setDestinationNetworks(DestinationNetworks value) {
        this.destinationNetworks = value;
    }

    /**
     * Gets the value of the routeSet property.
     * 
     * @return
     *     possible object is
     *     {@link RouteSet }
     *     
     */
    public RouteSet getRouteSet() {
        return routeSet;
    }

    /**
     * Sets the value of the routeSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteSet }
     *     
     */
    public void setRouteSet(RouteSet value) {
        this.routeSet = value;
    }

    /**
     * Gets the value of the projectId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getProjectId() {
        if (projectId == null) {
            return  0L;
        } else {
            return projectId;
        }
    }

    /**
     * Sets the value of the projectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProjectId(Long value) {
        this.projectId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the lockedForEdit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLockedForEdit() {
        if (lockedForEdit == null) {
            return false;
        } else {
            return lockedForEdit;
        }
    }

    /**
     * Sets the value of the lockedForEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLockedForEdit(Boolean value) {
        this.lockedForEdit = value;
    }

    /**
     * Gets the value of the lockedForHistory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLockedForHistory() {
        if (lockedForHistory == null) {
            return false;
        } else {
            return lockedForHistory;
        }
    }

    /**
     * Sets the value of the lockedForHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLockedForHistory(Boolean value) {
        this.lockedForHistory = value;
    }

}
