//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}table" minOccurs="0"/>
 *         &lt;element ref="{}sensor_type" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="crudFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_position" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="link_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="java_class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sensor_id_original" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_feed_id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="lane_number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="link_offset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="modStamp" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="health_status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}double">
 *             &lt;minInclusive value="0.0"/>
 *             &lt;maxInclusive value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "sensor")
public class Sensor {

    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    protected Parameters parameters;
    protected Table table;
    @XmlElement(name = "sensor_type")
    protected SensorType sensorType;
    @XmlAttribute(name = "crudFlag")
    protected String crudFlag;
    @XmlAttribute(name = "id", required = true)
    protected long id;
    @XmlAttribute(name = "link_position")
    protected Double linkPosition;
    @XmlAttribute(name = "link_id")
    protected Long linkId;
    @XmlAttribute(name = "java_class")
    protected String javaClass;
    @XmlAttribute(name = "sensor_id_original")
    protected String sensorIdOriginal;
    @XmlAttribute(name = "data_feed_id")
    protected Long dataFeedId;
    @XmlAttribute(name = "lane_number")
    protected Integer laneNumber;
    @XmlAttribute(name = "link_offset")
    protected Double linkOffset;
    @XmlAttribute(name = "modStamp")
    protected String modStamp;
    @XmlAttribute(name = "health_status")
    protected Double healthStatus;

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the sensorType property.
     * 
     * @return
     *     possible object is
     *     {@link SensorType }
     *     
     */
    public SensorType getSensorType() {
        return sensorType;
    }

    /**
     * Sets the value of the sensorType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorType }
     *     
     */
    public void setSensorType(SensorType value) {
        this.sensorType = value;
    }

    /**
     * Gets the value of the crudFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrudFlag() {
        return crudFlag;
    }

    /**
     * Sets the value of the crudFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrudFlag(String value) {
        this.crudFlag = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the linkPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLinkPosition() {
        return linkPosition;
    }

    /**
     * Sets the value of the linkPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLinkPosition(Double value) {
        this.linkPosition = value;
    }

    /**
     * Gets the value of the linkId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLinkId() {
        return linkId;
    }

    /**
     * Sets the value of the linkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLinkId(Long value) {
        this.linkId = value;
    }

    /**
     * Gets the value of the javaClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaClass() {
        return javaClass;
    }

    /**
     * Sets the value of the javaClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaClass(String value) {
        this.javaClass = value;
    }

    /**
     * Gets the value of the sensorIdOriginal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSensorIdOriginal() {
        return sensorIdOriginal;
    }

    /**
     * Sets the value of the sensorIdOriginal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSensorIdOriginal(String value) {
        this.sensorIdOriginal = value;
    }

    /**
     * Gets the value of the dataFeedId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataFeedId() {
        return dataFeedId;
    }

    /**
     * Sets the value of the dataFeedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataFeedId(Long value) {
        this.dataFeedId = value;
    }

    /**
     * Gets the value of the laneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLaneNumber() {
        return laneNumber;
    }

    /**
     * Sets the value of the laneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLaneNumber(Integer value) {
        this.laneNumber = value;
    }

    /**
     * Gets the value of the linkOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLinkOffset() {
        return linkOffset;
    }

    /**
     * Sets the value of the linkOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLinkOffset(Double value) {
        this.linkOffset = value;
    }

    /**
     * Gets the value of the modStamp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModStamp() {
        return modStamp;
    }

    /**
     * Sets the value of the modStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModStamp(String value) {
        this.modStamp = value;
    }

    /**
     * Gets the value of the healthStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHealthStatus() {
        return healthStatus;
    }

    /**
     * Sets the value of the healthStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHealthStatus(Double value) {
        this.healthStatus = value;
    }

}
