//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 01:41:04 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="vehicle_type_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_in" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="link_out" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "weavingfactors")
public class Weavingfactors {

    @XmlValue
    protected String content;
    @XmlAttribute(name = "vehicle_type_id", required = true)
    protected long vehicleTypeId;
    @XmlAttribute(name = "link_in", required = true)
    protected long linkIn;
    @XmlAttribute(name = "link_out", required = true)
    protected long linkOut;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the vehicleTypeId property.
     * 
     */
    public long getVehicleTypeId() {
        return vehicleTypeId;
    }

    /**
     * Sets the value of the vehicleTypeId property.
     * 
     */
    public void setVehicleTypeId(long value) {
        this.vehicleTypeId = value;
    }

    /**
     * Gets the value of the linkIn property.
     * 
     */
    public long getLinkIn() {
        return linkIn;
    }

    /**
     * Sets the value of the linkIn property.
     * 
     */
    public void setLinkIn(long value) {
        this.linkIn = value;
    }

    /**
     * Gets the value of the linkOut property.
     * 
     */
    public long getLinkOut() {
        return linkOut;
    }

    /**
     * Sets the value of the linkOut property.
     * 
     */
    public void setLinkOut(long value) {
        this.linkOut = value;
    }

}
